apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: kubepractice
spec:
  selector:
    matchLabels:
      app: kubepractice
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: kubepractice
    spec:
      serviceAccountName: test-service-account
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: kubernetespractice
          image: kubernetespractice:A5 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          volumeMounts:
            - mountPath: "/filelocation"
              name: task-pv-storage
#          env:
#            - name: DB_USERNAME
#              valueFrom:
#                configMapKeyRef:
#                  name: authentication  # Refers to the ConfigMap
#                  key: username         # Key for the username
#            - name: DB_PASSWORD
#              valueFrom:
#                configMapKeyRef:
#                  name: authentication
#                  key: password         # Key for the password
#            - name: DB_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: authentication
#                  key: url