apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: kubepractice
spec:
  selector:
    matchLabels:
      app: kubepractice
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: kubepractice
    spec:
      containers:
        - name: kubernetespractice
          image: kubernetespractice:A3 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"