apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: kubepractice
spec:
  selector:
    matchLabels:
      app: kubepractice
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: kubepractice
    spec:
      containers:
        - name: kubernetespractice
          image: kubernetespractice:v2 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster